import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Devtter 🎁</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    <Link href="#">Devtter</Link>
                </h1>
                <nav className={styles.nav}>
                    <Link href="/timeline"> Timeline </Link>
                </nav>
            </main>
        </>
    );
}
