import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Button from '../components/Button';
import GitHub from '../components/Icons/GitHub';
import { loginWithGithub, onAuthStateChanged } from '../firebase/client';

export default function Home() {
    const [user, setUser] = useState(undefined);

    useEffect(() => {
        onAuthStateChanged(setUser);
    }, []);

    const handleClick = () => {
        loginWithGithub()
            .then(setUser) // => {
            //setUser(user);
            // const { username, avatar, url } = user;
            // console.log(user);
            // })
            .catch((error) => {
                console.log(error);
            });
    };
    return (
        <>
            <Head>
                <title>Devtter 🎁</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <div className={styles.centrar}>
                <main className={styles.main}>
                    <section className={styles.sectionHome}>
                        <Image
                            src='/demon-slayer.svg'
                            className={styles.logo}
                            width={90}
                            height={90}
                            alt='Logo'
                        />
                        <h1 className={styles.h1}>Devtter</h1>
                        <h2 className={styles.h2}>
                            Talk about development <br /> with developers
                        </h2>
                        <div className={styles.button}>
                            {user === null && (
                                <Button onClick={handleClick}>
                                    <GitHub
                                        fill='#fff'
                                        width={22}
                                        height={22}
                                    />{' '}
                                    Login with GitHub
                                </Button>
                            )}
                            {user && user.avatar && (
                                <div>
                                    <picture>
                                        <source srcSet={user.avatar} />
                                        <img
                                            src={user.avatar}
                                            alt={user.username}
                                        />
                                    </picture>
                                    <strong> {user.username} </strong>
                                </div>
                            )}
                        </div>
                    </section>
                </main>
            </div>
        </>
    );
}
